apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: w52tjlvg8-go
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-go:811956ca06c84eb04f316c089d135e80ae1e9c24@sha256:b56f6270ec528c0fec8f6471da6e1ecc01bb5b69cfe1b1fc34a209cc1d5d3f3a
          name: container-image
